spring:
  datasource:
    url: jdbc:mysql://mysql-d6efdab-gigasmash476996-97a8.c.aivencloud.com:28461/defaultdb?useSSL=true&serverTimezone=UTC
    username: avnadmin
    password: AVNS_h3hqtEp95X_ViDP3-y6
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 18349381843-j11hhhlf6rdi8q65boo81miboden65t1.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
  server:
    servlet:
      session:
        cookie:
          same-site: none
          secure: true